import type { TenantContext } from '@platform/contracts';

export const PERMISSIONS = {
  ALL: '*',
  // Plataforma
  PLATFORM_DISTRIBUTOR_WRITE: 'platform:distributor:write',
  PLATFORM_DISTRIBUTOR_READ: 'platform:distributor:read',
  PLATFORM_CLIENT_READ: 'platform:client:read',
  PLATFORM_PLAN_WRITE: 'platform:plan:write',
  PLATFORM_PAYMENT_READ: 'platform:payment:read',
  PLATFORM_COMMISSION_READ: 'platform:commission:read',
  PLATFORM_PAYOUT_WRITE: 'platform:payout:write',
  PLATFORM_AUDIT_READ: 'platform:audit:read',
  PLATFORM_SUPPORT_START: 'platform:support:start',

  // Distribuidor
  DISTRIBUTOR_CLIENT_WRITE: 'distributor:client:write',
  DISTRIBUTOR_CLIENT_READ: 'distributor:client:read',
  DISTRIBUTOR_AGENT_WRITE: 'distributor:agent:write',
  DISTRIBUTOR_AGENT_READ: 'distributor:agent:read',
  DISTRIBUTOR_CHANNEL_WRITE: 'distributor:channel:write',
  DISTRIBUTOR_KNOWLEDGE_WRITE: 'distributor:knowledge:write',
  DISTRIBUTOR_WEBHOOK_WRITE: 'distributor:webhook:write',
  DISTRIBUTOR_COMMISSION_READ: 'distributor:commission:read',
  DISTRIBUTOR_BRANDING_WRITE: 'distributor:branding:write',
  DISTRIBUTOR_INBOX_READ: 'distributor:inbox:read',
  DISTRIBUTOR_INBOX_WRITE: 'distributor:inbox:write',

  // Cliente
  CLIENT_AGENT_READ: 'client:agent:read',
  CLIENT_INBOX_READ: 'client:inbox:read',
  CLIENT_INBOX_WRITE: 'client:inbox:write',
  CLIENT_CONTACT_READ: 'client:contact:read',
  CLIENT_CONTACT_WRITE: 'client:contact:write',
  CLIENT_KNOWLEDGE_READ: 'client:knowledge:read',
  CLIENT_USAGE_READ: 'client:usage:read',
  CLIENT_BILLING_READ: 'client:billing:read',
  CLIENT_BILLING_WRITE: 'client:billing:write',
  CLIENT_USER_INVITE: 'client:user:invite',
  CLIENT_PROMPT_READ: 'client:prompt:read',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const hasPermission = (ctx: TenantContext, permission: Permission): boolean => {
  if (ctx.permissions.includes('*')) return true;
  return ctx.permissions.includes(permission);
};

export const requirePermission = (ctx: TenantContext, permission: Permission): void => {
  if (!hasPermission(ctx, permission)) {
    throw new Error(`FORBIDDEN: missing permission ${permission}`);
  }
};

type PermissionSet = Set<string>;

export const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  PLATFORM_SUPER_ADMIN: [PERMISSIONS.ALL],
  PLATFORM_SUPPORT: [
    PERMISSIONS.PLATFORM_DISTRIBUTOR_READ,
    PERMISSIONS.PLATFORM_CLIENT_READ,
    PERMISSIONS.PLATFORM_AUDIT_READ,
    PERMISSIONS.PLATFORM_SUPPORT_START,
  ],
  PLATFORM_FINANCE: [
    PERMISSIONS.PLATFORM_PAYMENT_READ,
    PERMISSIONS.PLATFORM_COMMISSION_READ,
    PERMISSIONS.PLATFORM_PAYOUT_WRITE,
  ],
  PLATFORM_ANALYST: [
    PERMISSIONS.PLATFORM_DISTRIBUTOR_READ,
    PERMISSIONS.PLATFORM_CLIENT_READ,
    PERMISSIONS.PLATFORM_COMMISSION_READ,
  ],
  DISTRIBUTOR_ADMIN: [
    PERMISSIONS.DISTRIBUTOR_CLIENT_WRITE,
    PERMISSIONS.DISTRIBUTOR_CLIENT_READ,
    PERMISSIONS.DISTRIBUTOR_AGENT_WRITE,
    PERMISSIONS.DISTRIBUTOR_AGENT_READ,
    PERMISSIONS.DISTRIBUTOR_CHANNEL_WRITE,
    PERMISSIONS.DISTRIBUTOR_KNOWLEDGE_WRITE,
    PERMISSIONS.DISTRIBUTOR_WEBHOOK_WRITE,
    PERMISSIONS.DISTRIBUTOR_COMMISSION_READ,
    PERMISSIONS.DISTRIBUTOR_BRANDING_WRITE,
    PERMISSIONS.DISTRIBUTOR_INBOX_READ,
    PERMISSIONS.DISTRIBUTOR_INBOX_WRITE,
  ],
  DISTRIBUTOR_IMPLEMENTER: [
    PERMISSIONS.DISTRIBUTOR_CLIENT_READ,
    PERMISSIONS.DISTRIBUTOR_AGENT_WRITE,
    PERMISSIONS.DISTRIBUTOR_AGENT_READ,
    PERMISSIONS.DISTRIBUTOR_CHANNEL_WRITE,
    PERMISSIONS.DISTRIBUTOR_KNOWLEDGE_WRITE,
    PERMISSIONS.DISTRIBUTOR_INBOX_READ,
  ],
  DISTRIBUTOR_SUPPORT: [
    PERMISSIONS.DISTRIBUTOR_CLIENT_READ,
    PERMISSIONS.DISTRIBUTOR_AGENT_READ,
    PERMISSIONS.DISTRIBUTOR_INBOX_READ,
    PERMISSIONS.DISTRIBUTOR_INBOX_WRITE,
  ],
  DISTRIBUTOR_SALES: [
    PERMISSIONS.DISTRIBUTOR_CLIENT_WRITE,
    PERMISSIONS.DISTRIBUTOR_CLIENT_READ,
    PERMISSIONS.DISTRIBUTOR_COMMISSION_READ,
  ],
  DISTRIBUTOR_ANALYST: [
    PERMISSIONS.DISTRIBUTOR_CLIENT_READ,
    PERMISSIONS.DISTRIBUTOR_AGENT_READ,
    PERMISSIONS.DISTRIBUTOR_COMMISSION_READ,
    PERMISSIONS.DISTRIBUTOR_INBOX_READ,
  ],
  DISTRIBUTOR_READ_ONLY: [
    PERMISSIONS.DISTRIBUTOR_CLIENT_READ,
    PERMISSIONS.DISTRIBUTOR_AGENT_READ,
    PERMISSIONS.DISTRIBUTOR_INBOX_READ,
  ],
  CLIENT_ADMIN: [
    PERMISSIONS.CLIENT_AGENT_READ,
    PERMISSIONS.CLIENT_INBOX_READ,
    PERMISSIONS.CLIENT_INBOX_WRITE,
    PERMISSIONS.CLIENT_CONTACT_READ,
    PERMISSIONS.CLIENT_CONTACT_WRITE,
    PERMISSIONS.CLIENT_KNOWLEDGE_READ,
    PERMISSIONS.CLIENT_USAGE_READ,
    PERMISSIONS.CLIENT_BILLING_READ,
    PERMISSIONS.CLIENT_BILLING_WRITE,
    PERMISSIONS.CLIENT_USER_INVITE,
    PERMISSIONS.CLIENT_PROMPT_READ,
  ],
  CLIENT_MANAGER: [
    PERMISSIONS.CLIENT_AGENT_READ,
    PERMISSIONS.CLIENT_INBOX_READ,
    PERMISSIONS.CLIENT_INBOX_WRITE,
    PERMISSIONS.CLIENT_CONTACT_READ,
    PERMISSIONS.CLIENT_USAGE_READ,
    PERMISSIONS.CLIENT_BILLING_READ,
  ],
  CLIENT_HUMAN_AGENT: [
    PERMISSIONS.CLIENT_INBOX_READ,
    PERMISSIONS.CLIENT_INBOX_WRITE,
    PERMISSIONS.CLIENT_CONTACT_READ,
  ],
  CLIENT_ANALYST: [
    PERMISSIONS.CLIENT_AGENT_READ,
    PERMISSIONS.CLIENT_INBOX_READ,
    PERMISSIONS.CLIENT_USAGE_READ,
  ],
  CLIENT_READ_ONLY: [PERMISSIONS.CLIENT_AGENT_READ, PERMISSIONS.CLIENT_INBOX_READ],
};

export const permissionsForRoles = (roles: string[]): string[] => {
  const result: PermissionSet = new Set();
  for (const role of roles) {
    const perms = ROLE_PERMISSIONS[role];
    if (!perms) continue;
    for (const p of perms) result.add(p);
  }
  if (result.has(PERMISSIONS.ALL)) return [PERMISSIONS.ALL];
  return Array.from(result);
};
